name: Hank Quinlan, Horrible Cop
markdown: kramdown
defaults:
- scope:
    path: ''
    type: post
  values:
    layout: default
- scope:
    path: ''
    type: npms
  values:
    layout: default
collections:
 npms:
  output: true
  
 
